// <auto-generated />
using System;
using System.Collections.Generic;
using MedHub.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524163009_AddEnrollments")]
    partial class AddEnrollments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_manual_review");

                    b.Property<string>("TextAnswer")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text_answer");

                    b.Property<List<Guid>>("_selectedOptionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("selected_option_ids");

                    b.HasKey("Id")
                        .HasName("pk_attempt_answers");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_attempt_answers_attempt_id");

                    b.ToTable("attempt_answers", (string)null);
                });

            modelBuilder.Entity("MedHub.Domain.Checkpoints.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_checkpoint_answer_options");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_checkpoint_answer_options_question_id");

                    b.HasIndex("QuestionId", "IsCorrect")
                        .HasDatabaseName("ix_checkpoint_answer_options_question_id_is_correct");

                    b.ToTable("checkpoint_answer_options", (string)null);
                });

            modelBuilder.Entity("MedHub.Domain.Checkpoints.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<decimal>("Score")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("score");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_attempts");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_attempts_lesson_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_attempts_student_id");

                    b.HasIndex("StudentId", "LessonId", "Status")
                        .HasDatabaseName("ix_attempts_student_id_lesson_id_status");

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("MedHub.Domain.Checkpoints.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsGraded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_graded");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("Timestamp")
                        .HasColumnType("integer")
                        .HasColumnName("timestamp_seconds");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_checkpoints");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_checkpoints_video_id");

                    b.HasIndex("VideoId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_checkpoints_video_id_order_number");

                    b.HasIndex("VideoId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("ix_checkpoints_video_id_timestamp_seconds");

                    b.ToTable("checkpoints", (string)null);
                });

            modelBuilder.Entity("MedHub.Domain.Checkpoints.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowRetry")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_retry");

                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkpoint_id");

                    b.Property<string>("CorrectTextAnswer")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("correct_text_answer");

                    b.Property<bool>("RevealCorrectAnswer")
                        .HasColumnType("boolean")
                        .HasColumnName("reveal_correct_answer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_seconds");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_checkpoint_questions");

                    b.HasIndex("CheckpointId")
                        .HasDatabaseName("ix_checkpoint_questions_checkpoint_id");

                    b.HasIndex("CheckpointId", "Type")
                        .HasDatabaseName("ix_checkpoint_questions_checkpoint_id_type");

                    b.ToTable("checkpoint_questions", (string)null);
                });

            modelBuilder.Entity("MedHub.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_courses_creator_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_courses_status");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("MedHub.Domain.Enrollments.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EnrolledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_enrollments");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_enrollments_course_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_enrollments_status");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_enrollments_student_id");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollments_student_id_course_id");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("MedHub.Domain.Lessons.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<string>("ContentUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content_url");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_lessons_course_id");

                    b.HasIndex("OrderNumber")
                        .HasDatabaseName("ix_lessons_order_number");

                    b.HasIndex("CourseId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_lessons_course_id_order_number");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("MedHub.Domain.Media.VideoMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("upload_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_videos_lesson_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_videos_status");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("MedHub.Domain.Users.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "users:read"
                        },
                        new
                        {
                            Id = 2,
                            Name = "courses:read"
                        },
                        new
                        {
                            Id = 3,
                            Name = "courses:create"
                        },
                        new
                        {
                            Id = 4,
                            Name = "courses:update"
                        },
                        new
                        {
                            Id = 5,
                            Name = "courses:delete"
                        },
                        new
                        {
                            Id = 6,
                            Name = "courses:publish"
                        },
                        new
                        {
                            Id = 7,
                            Name = "courses:archive"
                        },
                        new
                        {
                            Id = 8,
                            Name = "lessons:read"
                        },
                        new
                        {
                            Id = 9,
                            Name = "lessons:create"
                        },
                        new
                        {
                            Id = 10,
                            Name = "lessons:update"
                        },
                        new
                        {
                            Id = 11,
                            Name = "lessons:delete"
                        },
                        new
                        {
                            Id = 12,
                            Name = "lessons:publish"
                        },
                        new
                        {
                            Id = 13,
                            Name = "lessons:archive"
                        },
                        new
                        {
                            Id = 14,
                            Name = "checkpoints:read"
                        },
                        new
                        {
                            Id = 15,
                            Name = "checkpoints:create"
                        },
                        new
                        {
                            Id = 16,
                            Name = "checkpoints:update"
                        },
                        new
                        {
                            Id = 17,
                            Name = "checkpoints:delete"
                        },
                        new
                        {
                            Id = 18,
                            Name = "checkpoints:publish"
                        },
                        new
                        {
                            Id = 19,
                            Name = "checkpoints:archive"
                        },
                        new
                        {
                            Id = 20,
                            Name = "questions:read"
                        },
                        new
                        {
                            Id = 21,
                            Name = "questions:create"
                        },
                        new
                        {
                            Id = 22,
                            Name = "questions:update"
                        },
                        new
                        {
                            Id = 23,
                            Name = "questions:delete"
                        },
                        new
                        {
                            Id = 24,
                            Name = "attempts:read"
                        },
                        new
                        {
                            Id = 25,
                            Name = "attempts:start"
                        },
                        new
                        {
                            Id = 26,
                            Name = "attempts:submit"
                        },
                        new
                        {
                            Id = 27,
                            Name = "attempts:cancel"
                        },
                        new
                        {
                            Id = 28,
                            Name = "attempts:evaluate"
                        },
                        new
                        {
                            Id = 33,
                            Name = "enrollments:read"
                        },
                        new
                        {
                            Id = 34,
                            Name = "enrollments:create"
                        },
                        new
                        {
                            Id = 35,
                            Name = "enrollments:cancel"
                        },
                        new
                        {
                            Id = 29,
                            Name = "media:read"
                        },
                        new
                        {
                            Id = 30,
                            Name = "media:upload"
                        },
                        new
                        {
                            Id = 31,
                            Name = "media:delete"
                        },
                        new
                        {
                            Id = 32,
                            Name = "media:process"
                        });
                });

            modelBuilder.Entity("MedHub.Domain.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Student"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("MedHub.Domain.Users.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 32
                        });
                });

            modelBuilder.Entity("MedHub.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MedHub.Infrastructure.BackgroundJobs.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("pk_role_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_role_user_users_id");

                    b.ToTable("role_user", (string)null);
                });

            modelBuilder.Entity("Answer", b =>
                {
                    b.HasOne("MedHub.Domain.Checkpoints.Attempt", null)
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_answers_attempt_attempt_id");
                });

            modelBuilder.Entity("MedHub.Domain.Checkpoints.AnswerOption", b =>
                {
                    b.HasOne("MedHub.Domain.Checkpoints.Question", null)
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checkpoint_answer_options_question_question_id");
                });

            modelBuilder.Entity("MedHub.Domain.Checkpoints.Question", b =>
                {
                    b.HasOne("MedHub.Domain.Checkpoints.Checkpoint", null)
                        .WithMany("Questions")
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checkpoint_questions_checkpoints_checkpoint_id");
                });

            modelBuilder.Entity("MedHub.Domain.Lessons.Lesson", b =>
                {
                    b.HasOne("MedHub.Domain.Courses.Course", null)
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_courses_course_id");
                });

            modelBuilder.Entity("MedHub.Domain.Media.VideoMaterial", b =>
                {
                    b.OwnsOne("MedHub.Domain.Media.ValueObjects.VideoTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("VideoMaterialId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("title");

                            b1.HasKey("VideoMaterialId");

                            b1.ToTable("videos");

                            b1.WithOwner()
                                .HasForeignKey("VideoMaterialId")
                                .HasConstraintName("fk_videos_videos_id");
                        });

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("MedHub.Domain.Users.RolePermission", b =>
                {
                    b.HasOne("MedHub.Domain.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("MedHub.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("MedHub.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_role_roles_id");

                    b.HasOne("MedHub.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_user_users_id");
                });

            modelBuilder.Entity("MedHub.Domain.Checkpoints.Attempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("MedHub.Domain.Checkpoints.Checkpoint", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MedHub.Domain.Checkpoints.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("MedHub.Domain.Courses.Course", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
